### ISSUE TITLE
scheduler attribute preempt_sort needs to be revisited

### ISSUE THREAD

**Issue by saritakh** [openpbs/openpbs#1185]
An unset of attribute should get it back to default value; which is not the case with scheduler attribute preempt_sort.
A recent scheduler enhancement updated configuration of sched parameter preempt_sort from 'sched_config' file to qmgr interface; whose change summary is as below:

**Old sched_config behavior:**
Default:
	preempt_sort = min_time_since_start
Non-default:
	#preempt_sort = min_time_since_start

**New qmgr behavior:**
Default:
	preempt_sort = min_time_since_start
Non-default: qmgr unset action
	<Attribute removed from qmgr "p sched">

Now in order to get this attribute back to default value; we actually need to set it back to "min_time_since_start". By convention, the "unset" of "preempt_sort" should result in default value i.e. min_time_since_start; which is not the case right now.  
Right now once we unset "preempt_sort", in order to get it to back to default value, we need to remember the string "min_time_since_start" and set the same.
This is not the case with other scheduler parameters as shown below:

[root@n27 ~]# qmgr -c "print sched"
...
set sched scheduling = True
set sched scheduler_iteration = 600
set sched state = idle
set sched preempt_queue_prio = 150
set sched preempt_prio = "express_queue, normal_jobs"
set sched preempt_order = SCR
set sched preempt_sort = min_time_since_start
[root@n27 ~]# qmgr -c "unset sched preempt_sort"
[root@n27 ~]# qmgr -c "print sched"
...
set sched scheduling = True
set sched scheduler_iteration = 600
set sched state = idle
set sched preempt_queue_prio = 150
set sched preempt_prio = express_queue, normal_jobs
set sched preempt_order = SCR
[root@n27 ~]# qmgr -c "unset sched preempt_prio"
[root@n27 ~]# qmgr -c "print sched"
...
set sched scheduling = True
set sched scheduler_iteration = 600
set sched state = idle
set sched preempt_queue_prio = 150
set sched preempt_prio = express_queue, normal_jobs
set sched preempt_order = SCR
[root@n27 ~]# qmgr -c "u sched preempt_queue_prio"
[root@n27 ~]# qmgr -c "p sched"
...
set sched scheduling = True
set sched scheduler_iteration = 600
set sched state = idle
set sched preempt_queue_prio = 150
set sched preempt_prio = express_queue, normal_jobs
set sched preempt_order = SCR
[root@n27 ~]# qmgr -c "u sched preempt_order"
[root@n27 ~]# qmgr -c "p sched"
...
set sched scheduling = True
set sched scheduler_iteration = 600
set sched state = idle
set sched preempt_queue_prio = 150
set sched preempt_prio = express_queue, normal_jobs
set sched preempt_order = SCR
[root@n27 ~]#

**Proposed solution:**
- Remove preempt_sort configuration since it has only one value and have the minimum time since start as default behaviour. Can be added back when we enhance the sorting methods. 
- Have two values for preempt_sort so that it can be reverted to the default behavior when unset.

**Reference:**
RFE Discussion - https://github.com/PBSPro/pbspro/pull/1131

**Comment by agrawalravi90** [comment]
Hi @saritakh I have some thoughts on this, but we use the forums for discussing design changes, so can you please open a topic there?

**Comment by vstumpf** [comment]
Fixed in  1b3507b
