### ISSUE TITLE
add autogen.sh to the %build section of the spec file

### ISSUE THREAD

**Issue by sstcdev** [openpbs/openpbs#1205]
we need to add
[ -f configure ] || ./autogen.sh
to the %build section of both pbspro.spec and pbspro.spec.in

With above modification, 
 we can build RPMs with rpmbuild -ta SOURCE/pbspro-19.1.2.tar.gz
 both 
  from
  https://github.com/PBSPro/pbspro/releases/download/v19.1.2/pbspro-19.1.2.tar.gz
  and 
  from
  https://github.com/PBSPro/pbspro/archive/v19.1.2.tar.gz

And https://github.com/PBSPro/pbspro/releases/download/v19.1.2/pbspro-19.1.2.tar.gz may not be required to be listed.

**Comment by vstumpf** [comment]
Fixed in  369b342
