### ISSUE TITLE
cgroup hook should tolerate missing hook events

### ISSUE THREAD

**Issue by mike0042** [openpbs/openpbs#1206]
The cgroup hook relies on certain hook events to be present. This prevents sites from taking a newer version of the hook and running it with an older version of PBS Pro. For example, PBS Pro 19.x provides an execjob_abort event that is not present in 18.x. If the hook checked for the existence of an event prior to registering it then it would be backward compatible. One way to accomplish this is as follows:

```
import pbs
if ’EXECJOB_ABORT’ in dir(pbs):
    self.hook_events[pbs.EXECJOB_ABORT] = { 
       'name': 'execjob_abort', 
       'handler': self._execjob_end_handler 
    }
```

It would also be possible to place the registration within a try/except block and ignore any errors if the event is not present.

**Comment by vstumpf** [comment]
Fixed in 9a09e8d75a3df4fd513c893329b69b9d4804e0a0
