### ISSUE TITLE
qsub: cannot access script file when TMPDIR is set to a long value

### ISSUE THREAD

**Issue by jnewman-altair** [openpbs/openpbs#1321]
Hello,
I'm reporting an issue with qsub whereby setting TMPDIR to a long string is resulting in an error "qsub: cannot access script file". In Cadence's case, it is resulting in a segfault. I have verified the same behavior appears in 19.1.1 and 19.1.2.
```
jnewman@hydra:~> qstat --version
pbs_version = 19.1.1
jnewman@hydra:~> qsub -l select=1:ncpus=1:mem=1024MB -mn -o /dev/null -e /dev/null -k oed -W umask=022 -- sleep 5
3012.hydra
jnewman@hydra:~> export TMPDIR=/dv/scratch/relntr/vip_logs/patch_xcelium5_gather_update.073119-110237/venus_in_grid_scratch_2019-Aug-05-20-12-50_16701/tmpdir9999
jnewman@hydra:~> qsub -l select=1:ncpus=1:mem=1024MB -mn -o /dev/null -e /dev/null -k oed -W umask=022 -- sleep 5                                               
qsub: cannot access script file
jnewman@hydra:~> export TMPDIR=/dv/scratch/relntr/vip_logs/patch_xcelium5_gather_update.073119-110237/venus_in_grid_scratch_2019-Aug-05-20-12-50_16701         
jnewman@hydra:~> qsub -l select=1:ncpus=1:mem=1024MB -mn -o /dev/null -e /dev/null -k oed -W umask=022 -- sleep 5                                               
qsub: cannot access script file
jnewman@hydra:~> touch $TMPDIR/test.file
jnewman@hydra:~> rm -f $TMPDIR/test.file
jnewman@hydra:~> export TMPDIR=/dv/scratch/relntr/vip_logs/patch_xcelium5_gather_update.073119-110237
jnewman@hydra:~> qsub -l select=1:ncpus=1:mem=1024MB -mn -o /dev/null -e /dev/null -k oed -W umask=022 -- sleep 5
3014.hydra
```

**Comment by pnarwa** [comment]
Hello,
 
qsub throws a segmentation fault if the shell on which qsub is executed has a TMPDIR ENV variable with the length of the string > 122 characters, please see below:
 
bash-3.2$ export TMPDIR=/dv/scratch/relntr/vip_logs/patch_xcelium5_gather_update.073119-110237/venus_in_grid_scratch_2019-Aug-05-20-12-50_16701/tmpdir9999

bash-3.2$ qsub -l select=1:ncpus=1:mem=1024MB -mn -o /dev/null -e /dev/null -k oed -W umask=022 -- sleep 5
Segmentation fault
 
If the size of the TMPDIR variable is reduced to 122 characters or less, qsub works fine:
 
bash-3.2$ export TMPDIR=/dv/scratch/relntr/vip_logs/patch_xcelium5_gather_update.073119-110237/venus_in_grid_scratch_2019-Aug-05-20-12-50_16701/tm
bash-3.2$ qsub -l select=1:ncpus=1:mem=1024MB -mn -o /dev/null -e /dev/null -k oed -W umask=022 -- sleep 5
2485876.nfpbsm02

Attached is the strace from the qsub command.

bash-4.1$ qsub --version
pbs_version = 19.0.0
bash-4.1$
[qsub_strace.log](https://github.com/PBSPro/pbspro/files/3663976/qsub_strace.log)

**Comment by scc138** [comment]
This was fixed in master branch via https://github.com/PBSPro/pbspro/pull/1017
