### ISSUE TITLE
Server failing to recover queue on restart and having panic shutdown

### ISSUE THREAD

**Issue by saritakh** [openpbs/openpbs#1383]
Server is unable to recover a queue having preempt_targets set as a queue and has a panic shutdown when we try to create this un-recovered queue.

Steps to reproduce:

1. Create workq2 and workq3
2. On workq2 set preempt_targets as a queu
set queue workq2 preempt_targets=queue=workq3		
3. Restart PBS
/etc/init.d/pbs restart
PBS fails to recover workq2!
4. Try to create workq2
create queue workq2 queue_type=e,enabled=t,started=t
The server has a panic shutdown!

**Comment by vstumpf** [comment]
Fixed in 36458ef
