### ISSUE TITLE
pbs_mom core dump in post_reply()

### ISSUE THREAD

**Issue by drtoss** [openpbs/openpbs#1469]
If a sister mom has trouble talking to the pbs_comm, the mom can core dump on EOJ hook completion:

```
(gdb) bt
 #0  0x000000000046d312 in post_reply (pjob=0x908160, err=0) at /home6/csjohn12/Projects/drtoss19/src/resmom/requests.c:1205
 #1  0x0000000000453737 in reply_hook_bg (pjob=0x908160) at /home6/csjohn12/Projects/drtoss19/src/resmom/mom_hook_func.c:3479
 #2  0x0000000000453969 in mom_process_background_hooks (ptask=0x7a4e00) at /home6/csjohn12/Projects/drtoss19/src/resmom/mom_hook_func.c:3548
 #3  0x00000000004ceaa0 in dispatch_task (ptask=0x7a4e00) at /home6/csjohn12/Projects/drtoss19/src/lib/Libutil/work_task.c:142
 #4  0x00000000004ceda2 in default_next_task () at /home6/csjohn12/Projects/drtoss19/src/lib/Libutil/work_task.c:308
 #5  0x00000000004640d8 in main (argc=1, argv=0x7fffffffed18) at /home6/csjohn12/Projects/drtoss19/src/resmom/mom_main.c:9803
 (gdb) p pjob->ji_hosts
 $5 = (hnodent *) 0x0

```
Suggested patch that prevents the core dump. However, someone with more knowledge should see how we got here with ji_hosts NULL:

```
diff --git a/src/resmom/requests.c b/src/resmom/requests.c
index 94a8ee01..f31febdb 100644
--- a/src/resmom/requests.c
+++ b/src/resmom/requests.c
@@ -1201,6 +1201,11 @@ post_reply(job *pjob, int err)
 
        if (pjob->ji_postevent == TM_NULL_EVENT)        /* no event */
                return;
+       if (pjob->ji_hosts == NULL) {           /* No one to talk to */
+               pjob->ji_postevent = TM_NULL_EVENT;
+               pjob->ji_taskid = TM_NULL_TASK;
+               return;
+       }
 
        stream = pjob->ji_hosts[0].hn_stream;   /* MS stream */
        cookie = pjob->ji_wattr[(int)JOB_ATR_Cookie].at_val.at_str;

```

**Comment by scc138** [comment]
Hello @drtoss, Altair has been investigating this further and so far we have been unable to reproduce the problem.  Do you have logs from a time the crash occurred that you can share with us?

**Comment by drtoss** [comment]
Sorry, the test system where these crashes were occurring has been reimaged and the logs lost. However, we expanded the patch beyond what I showed above to including logging the event should it happen. It has been several months without any such log messages.

My guess is that the base cause was an issue we were having with TPP and separate networks such that the server could talk to any node, but some sets of nodes could not talk to other sets of nodes. I think that once the TPP issue was fixed, the situation that leads to the NULL ji_hosts no longer occurs.

You can close the ticket. (But we'll keep our patch, just in case :-)

**Comment by subhasisb** [comment]
Hi @drtoss I took a look and I think your explanation makes complete sense. In that particular situation, the IM_JOIN_JOB never reached a sister mom (due to separate networks) - however, the server can talk to all the moms, so when server sends the IS_DISCARD_JOB message to a sister which did never get the JOIN_JOB it accesses the still NULL ji_hosts pointer and crashes. I think,  the IS_DISCARD_JOB  is a ONLY case? Could other stuff like checkpointing also suffer? We do have a lot of unprotected access of ji_hosts in the mom code, so we should guard atleast the vulnerable ones (including this one)
