### ISSUE TITLE
Recipe to start PBS without systemd

### ISSUE THREAD

**Issue by espenfl** [openpbs/openpbs#1850]
We are building a few containers which we will use to test the scheduler interfaces in AiiDA. In that process I am trying to build these without systemd. But I am a bit stuck with OpenPBS. Is there a recipe for how to prepare and launch OpenPBS without systemd? We would like to avoid it if we can. Or, maybe even better, do anyone have a `Dockerfile` that can be used for this or can point me in the right direction? Thanks in advance.

**Comment by vstumpf** [comment]
There's an init script that is installed: /etc/init.d/pbs 
arguments are: start, stop, restart, status

Those shouldn't require systemd.
