### ISSUE TITLE
Node scheduling

### ISSUE THREAD

**Issue by leebobby** [openpbs/openpbs#2132]
Hi,
I want to know how openpbs uses nodes to schedule, not the number of CPU cores. 
The problem is:
If core scheduling is used, the memory is insufficient. If the CPU cores of a node are not used up, jobs will not be scheduled to the next node.
example：
![image](https://user-images.githubusercontent.com/16457850/99870078-27449300-2c0b-11eb-90f7-f5c09750397c.png)
![image](https://user-images.githubusercontent.com/16457850/99870093-44796180-2c0b-11eb-9127-5ed63a7c233e.png)

Thx very much!

**Comment by vstumpf** [comment]
Your job can request a `sharing` value of `exclhost`, with your job, and your job will take all the resources on the node.

If you're an admin, you can set the `sharing` attribute of the nodes to `force_exclhost` (or `force_excl`) to force jobs using all the node's resources.

**Comment by agrawalravi90** [comment]
you can also add mem as a resource that's requested by each job. That way scheduler will know when memory is insufficient and stop scheduling jobs on that node. Either the job submitters can request it, or the admin can add a 'default' mem that will be added as a request for all jobs in the absence of user provided mem.

**Comment by bhroam** [comment]
My suggestions is to not use the old deprecated 'nodes' syntax and use the modern 'select' syntax.  This allows you to request chunks of resources.  These chunks of resources can be a request for nodes, or a request where multiple chunks of resources are placed on one node.  It sounds like you want the former.

You want something like: -lselect=N:ncpus=71:mem=M -lplace=scatter
where N is the number of nodes (your example had 1) and M is the amount of mem you need on your nodes.

**Comment by leebobby** [comment]
> My suggestions is to not use the old deprecated 'nodes' syntax and use the modern 'select' syntax. This allows you to request chunks of resources. These chunks of resources can be a request for nodes, or a request where multiple chunks of resources are placed on one node. It sounds like you want the former.
> 
> You want something like: -lselect=N:ncpus=71:mem=M -lplace=scatter
> where N is the number of nodes (your example had 1) and M is the amount of mem you need on your nodes.
> 
> If you want no one else to use the node, do what @vstumpf suggested and request -lplace=excl or -lplace=exclhost (or use sharing). You combine the place directive together with colons, so -lplace=scatter:excl. You'll see the nodes go into state job-exclusive

Thanks @bhroam  @vstumpf   ! Appreciate for your help!
When I submit the task using the following method, I can implement node-based scheduling.
![image](https://user-images.githubusercontent.com/16457850/100056827-4ccada00-2e61-11eb-86fd-cbe21383374b.png)
However, @vstumpf  change the sharing attribute of the node is failed. The command output is as follows:
![image](https://user-images.githubusercontent.com/16457850/100058120-b51abb00-2e63-11eb-9e2d-ace6a5b96984.png)
[root@node26 ~]# qmgr -c 'set node node27 sharing=force_excl'
qmgr obj=node27 svr=default: Cannot set attribute, read only or insufficient permission  sharing
qmgr: Error (15003) returned from server

I entered the command as the root user, what's wrong the command?
Thanks again.

**Comment by leebobby** [comment]
> you can also add mem as a resource that's requested by each job. That way scheduler will know when memory is insufficient and stop scheduling jobs on that node. Either the job submitters can request it, or the admin can add a 'default' mem that will be added as a request for all jobs in the absence of user provided mem.

This method in my HPC not work, I use pbsnodes to view the memory of the current machine and specify the maximum memory when submitting the task. After the task is submitted, the pbsnodes status is still free.
![image](https://user-images.githubusercontent.com/16457850/100058557-7f2a0680-2e64-11eb-8483-08fd2639d799.png)
Still, thank you for your answer.

**Comment by agrawalravi90** [comment]
resources_available.mem never changes, it always remains set to the total memory. Please check the value of resources_assigned.mem, that should incrementally increase as you run jobs which request memory

**Comment by agrawalravi90** [comment]
I think the node will remain 'free' if it has any number of ncpus still available. But scheduler should stop scheduling jobs on it if the memory is filled up

**Comment by bhroam** [comment]
@leebobby if you want to only submit 1 job to the node, use -lplace=excl.  This will change the state of the node to job-exclusive.  @agrawalravi90 is right, memory won't change the state of the node.  It won't change on its own until all of its cpus are in use.  It will change to job-busy then.  If every job requests memory, the scheduler will not schedule any more jobs on a node because there is not enough memory free.

**Comment by leebobby** [comment]
> resources_available.mem never changes, it always remains set to the total memory. Please check the value of resources_assigned.mem, that should incrementally increase as you run jobs which request memory

I tried it and it should be OK, but the '-l mem' memory usage is hard to match the specified value.
![image](https://user-images.githubusercontent.com/16457850/100174617-ba314600-2f07-11eb-8d05-f478603e28d7.png)

I think @vstumpf  @bhroam 's method suits me better.
Thanks a lot.

**Comment by leebobby** [comment]
> @leebobby if you want to only submit 1 job to the node, use -lplace=excl. This will change the state of the node to job-exclusive. @agrawalravi90 is right, memory won't change the state of the node. It won't change on its own until all of its cpus are in use. It will change to job-busy then. If every job requests memory, the scheduler will not schedule any more jobs on a node because there is not enough memory free.

Thanks for your answer.
'-lplace=excl' I've tried this way. It's feasible.
I want know how to change sharing attribute; When I use the following command line, an error message is displayed.
![image](https://user-images.githubusercontent.com/16457850/100175085-b3570300-2f08-11eb-8e3a-9c4dd88a1446.png)

**Comment by vstumpf** [comment]
sharing can only be set by a vnodedef file or by an exechost startup hook.

See Section 3.4.4 in the admin guide
https://www.altair.com/pdfs/pbsworks/PBSAdminGuide2020.1.pdf (pdf warning)

**Comment by leebobby** [comment]
Thanks for your answer, @vstumpf  , My problem has been solved.
![image](https://user-images.githubusercontent.com/16457850/100585886-4046f580-3329-11eb-8daa-f49ee4b4b6cf.png)
But I'd like to ask you a few questions.
(1) My configure file is:
![image](https://user-images.githubusercontent.com/16457850/100586808-a84a0b80-332a-11eb-99ae-8e21517161b7.png)
when I insert config file and restart pbs, there is a error log, and sharing attr still default_shared
![image](https://user-images.githubusercontent.com/16457850/100586911-d7607d00-332a-11eb-950d-d73c8b59f1c3.png)
(2)when I use kill -INT <pbs_mom pid>, It made node down
![image](https://user-images.githubusercontent.com/16457850/100587038-0971df00-332b-11eb-8aa1-f99c382cb34c.png)

Finally, I use kill -HUP <pbs_mom pid> command and the setting is successful.

**Comment by vstumpf** [comment]
That's interesting, does the mom logs show anything?

**Comment by leebobby** [comment]
> That's interesting, does the mom logs show anything?
Thanks for your answer, my problem has solved by using the kill -HUP command.
&
The mom_log has the  same error as command return
![image](https://user-images.githubusercontent.com/16457850/104265611-f117e700-54c8-11eb-96ee-ec987042ffcb.png)
