### ISSUE TITLE
Bump PBS_BATCH_PROT_VER?

### ISSUE THREAD

**Issue by drtoss** [openpbs/openpbs#2158]
The code for issue 1953 [https://github.com/openpbs/openpbs/pull/1953] made a fundamental change to the protocol, such that the new executables hang when connecting to an older server. I believe this is sufficienly disruptive to require that PBS_BATCH_PROT_VER be bumped to a new version. If this were done, connections would immediately recognize the problem, rather than hang.

**Comment by subhasisb** [comment]
Sorry we missed bumping the version. We will take it up on priority and fix this. Thanks for pointing out.
