### ISSUE TITLE
How PBS_MOM start the process on multiple nodes, must MPI?

### ISSUE THREAD

**Issue by leebobby** [openpbs/openpbs#2211]
In PBSAdminGuide2020.1.pdf , I get below picture:
![image](https://user-images.githubusercontent.com/16457850/105359913-f4cb0c80-5c32-11eb-848b-0053ae8500a9.png)
and
![image](https://user-images.githubusercontent.com/16457850/105359947-feed0b00-5c32-11eb-8c3d-72bb57bfa393.png)
I want know, PBS must use MPI to start the process? 

Are there other methods to start computation process?

**Comment by vstumpf** [comment]
Doesn't have to be MPI, but if you want the pbs_moms to track the resource usage of the spawned processes, you need to use the tm (task manager) library.
OpenPBS has pbsdsh, which will use the tm library to spawn processes (tm_spawn) on the other nodes.
There's also pbs_attach, which will notify the local mom that a pid is part of a job (tm_attach), so it will be tracked and resource usage will be recorded.

**Comment by leebobby** [comment]
> Doesn't have to be MPI, but if you want the pbs_moms to track the resource usage of the spawned processes, you need to use the tm (task manager) library.
> OpenPBS has pbsdsh, which will use the tm library to spawn processes (tm_spawn) on the other nodes.
> There's also pbs_attach, which will notify the local mom that a pid is part of a job (tm_attach), so it will be tracked and resource usage will be recorded.

Thank you very much for your answer @vstumpf . But I have some questions.
I find a example code in pdfs which is similar to your answer :
![image](https://user-images.githubusercontent.com/16457850/105467762-1975c180-5cd1-11eb-8acc-d1ab3205c781.png)

When I test this example in my server,  I found a problem:
I want all server start 14 processes.
![image](https://user-images.githubusercontent.com/16457850/105468515-06afbc80-5cd2-11eb-9834-60f52ae43d62.png)
But in log, there is only 4 processes in all nodes.
![image](https://user-images.githubusercontent.com/16457850/105468649-28a93f00-5cd2-11eb-9af5-a43d2bed54b6.png)

So I'd like to ask you a few questions.
(1)Is there a block diagram to describe this process,  like following figure;
![image](https://user-images.githubusercontent.com/16457850/105469297-fc41f280-5cd2-11eb-87a2-af7f0a453bd3.png)
(2)Are processes on all nodes started on Vnode1?
(3)Before script start processes can I get rank_id?

PS:
a.out 's source code:
![image](https://user-images.githubusercontent.com/16457850/105469695-9e61da80-5cd3-11eb-8775-539251f799b0.png)

**Comment by vstumpf** [comment]
> I want all server start 14 processes.
> But in log, there is only 4 processes in all nodes.

This is because if you check $PBS_NODEFILE, there are only 4 hosts. You'll need to use mpiprocs for this:
> Number of MPI processes for this chunk. Cannot use sum from chunks as job-wide limit. The number of lines in PBS_NODEFILE is the sum of the values of mpiprocs for all chunks requested by the job. For each chunk with mpiprocs=P, the host name for that chunk is written to the PBS_NODEFILE P times.

So, your select line will look like:
`-l select="ncpus=5+mpiprocs=5:mem=1gb+ncpus=6+mpiprocs=6:mem=2gb+ncpus=3+mpiprocs=3:mem=2gb"`
 
> So I'd like to ask you a few questions.
> (1)Is there a block diagram to describe this process, like following figure;

I don't think so. 

> (2)Are processes on all nodes started on Vnode1?

If you're using the tm library, kind of. The tm library will tell the local mom to tell the remote moms to spawn a process.
So when you call pbsdsh, it talks to the local mom (on node27), to tell the mom on node26 to run `hostname`.

> (3)Before script start processes can I get rank_id?

I don't think you can get it before the processes start, but the environment of the process has `PBS_TASKNUM`
```
[vstumpf@shecil pbspro]$ qsub -I -lselect=2:ncpus=1
qsub: waiting for job 3002.shecil to start
qsub: job 3002.shecil ready
[vstumpf@shecil ~]$ env | grep PBS_TASKNUM
PBS_TASKNUM=1

[vstumpf@shecil ~]$ pbsdsh env
...
PBS_TASKNUM=00000002
...
PBS_TASKNUM=00000003
```

BTW, there's no such thing as $NNODES in pbs,

**Comment by leebobby** [comment]
Thank you very much for your answer @vstumpf . I've solved the problem of starting multiple processes and I still have some problems when I test the demo.
According to my test results, I find that both of pbsdsh and pbstmrsh can start the computing processes.
My first script:
![image](https://user-images.githubusercontent.com/16457850/105706115-1803fd80-5f4c-11eb-966e-1be96e3de2dc.png)
Results:
![image](https://user-images.githubusercontent.com/16457850/105706178-2eaa5480-5f4c-11eb-990b-dac10b5b6593.png)
![image](https://user-images.githubusercontent.com/16457850/105706194-323ddb80-5f4c-11eb-945c-85f9a20ca062.png)
![image](https://user-images.githubusercontent.com/16457850/105706201-35d16280-5f4c-11eb-8877-ab6b674ef9aa.png)

My second script:
![image](https://user-images.githubusercontent.com/16457850/105706241-42ee5180-5f4c-11eb-9a94-ce823f1fc2ea.png)
Results:
![image](https://user-images.githubusercontent.com/16457850/105706319-57cae500-5f4c-11eb-91a9-6d531cd84c7a.png)
![image](https://user-images.githubusercontent.com/16457850/105706344-61544d00-5f4c-11eb-8585-0f6e36fc7cf0.png)
![image](https://user-images.githubusercontent.com/16457850/105706363-67e2c480-5f4c-11eb-99e9-9807dc1e11ed.png)

In PBSReferenceGuide.pdf, I get:
![image](https://user-images.githubusercontent.com/16457850/105706466-8a74dd80-5f4c-11eb-82c3-dc6edd3f62fe.png)
![image](https://user-images.githubusercontent.com/16457850/105706501-9791cc80-5f4c-11eb-978c-99efde4c8db2.png)
![image](https://user-images.githubusercontent.com/16457850/105706608-b7c18b80-5f4c-11eb-9fcd-2b21c2c7d2a3.png)
Therefore, the three commands can be used to start processes on the vnode,which is consistent with the test result.
But I think pbs_attach should be invoked to ensure that resources can be monitored. So I want to know what the script is right.

Another question:
(1) In first vnode, there is a extra task(00000001), What is its function?
(2) Can the task ID be used as the logical number of a process, such as the rank ID of the MPI?

**Comment by vstumpf** [comment]
> (1) In first vnode, there is a extra task(00000001), What is its function?

I believe that is the job script running, which will do the spawning of tasks.

> (2) Can the task ID be used as the logical number of a process, such as the rank ID of the MPI?

I think so, they seem to be unique for a job.

> But I think pbs_attach should be invoked to ensure that resources can be monitored. So I want to know what the script is right.

You don't need pbs_attach for pbs_dsh or pbs_tmrsh. As you can see in your examples, the mom log is printing the tasks started, meaning the mom is tracking the resources of it.
You only need to use pbs attach if you're not using the tm library, like with ssh.

**Comment by leebobby** [comment]
> > (1) In first vnode, there is a extra task(00000001), What is its function?
> 
> I believe that is the job script running, which will do the spawning of tasks.
> 
> > (2) Can the task ID be used as the logical number of a process, such as the rank ID of the MPI?
> 
> I think so, they seem to be unique for a job.
> 
> > But I think pbs_attach should be invoked to ensure that resources can be monitored. So I want to know what the script is right.
> 
> You don't need pbs_attach for pbs_dsh or pbs_tmrsh. As you can see in your examples, the mom log is printing the tasks started, meaning the mom is tracking the resources of it.
> You only need to use pbs attach if you're not using the tm library, like with ssh.

Thank you very much!  @vstumpf , Your answer helped me a lot.

**Comment by vstumpf** [comment]
I'm going to close this, if you need more info please reopen it or post on the forums. http://community.openpbs.org/c/users-site-administrators
