### ISSUE TITLE
failed in Rocky linux 8.4 with python3.8.8

### ISSUE THREAD

**Issue by friendly0115** [openpbs/openpbs#2476]
Dear all,
I failed the installation with the package on the master branch on the Rocky linux 8.4 with python 3.8.8.
 
Is there some way to fix this?

thank you all

**Comment by svoboda77** [comment]
Installation on Rocky Linux 8.4 fails because of missing library libhwloc.so.5. On Centos 8 this library is included in package compat-hwloc1, but this package is missing in RL repositories.
