### ISSUE TITLE
A lock is not released in the thread?

### ISSUE THREAD

**Issue by ryancaicse** [openpbs/openpbs#2495]
Dear developers, it seems the lock `cleanup_lock` is not released correctly?

https://github.com/openpbs/openpbs/blob/91bd1d5d4dcf58f031016826f2241d69399bcfc2/src/scheduler/pbs_sched_utils.cpp#L152-L173

Best,

**Comment by drtoss** [comment]
I am not an expert on threads, but I believe this is okay. That is, the routine this code is in uses the mutex to make sure only one thread executes the abort code. If a second thread tries to run, it hangs or goes away via pthread_exit(). The straight code path proceeds to either abort(), execv(), or exit(), all of which discard any mutexes.
