### ISSUE TITLE
pbs_server won't survive restart due to job_sort_formula

### ISSUE THREAD

**Issue by erdchris** [openpbs/openpbs#2530]
Upon restart, all primary daemons will start but not pbs_server. Last line in logs is:

03/26/2022 09:29:00;0001;Server@service0;Svr;Server@service0;PBS server internal error (15011) in decode_attr_db, Action function failed for job_sort_formula attr, errn 15011

If I forcibly remove job_sort_formula from datastore, pbs_server will start. It will accept the formula in qmgr. PBS will run with this formula. But will repeat the process of dying if the formula exists upon restart. I find a core in server_logs.

set server job_sort_formula = "queue_priority + (0.005 * ncpus) + (0.000277778 * eligible_time) + paws + bias"
or without spaces
set server job_sort_formula = "queue_priority+(0.005\*ncpus)+(0.000277778\*eligible_time)+paws+bias"

In psql it looks like:

"job_sort_formula"=>"11.queue_priority + (0.005 * ncpus) + (0.000277778 * eligible_time) + paws + bias"
or without spaces
"job_sort_formula"=>"11.queue_priority+(0.005\*ncpus)+(0.000277778\*eligible_time)+paws+bias"

This formula exists without incident on other PBSPro systems, including version 19 and 2020.

OpenPBS was the latest pull as of Dec 2021. Version says 20.0.0. Custom resources mentioned are:

create resource bias
set resource bias type = float
set resource bias flag = r
set server resources_default.bias = 0
create resource paws
set resource paws type = float
set resource paws flag = r
set server resources_default.paws = 0

Thanks, Chris

**Comment by pmrich** [comment]
PR #2533 seems to have fixed this and has been merged into master.  It was working in my test environment when I pulled it down.

**Comment by bayucan** [comment]
Yes, PR 2533 fixed this problem, so I'm closing this ticket.
