### ISSUE TITLE
qsub -V option not working.

### ISSUE THREAD

**Issue by Crispy13** [openpbs/openpbs#2611]
It worked with pbs_version = 2021.1.3.20220217134230, but not with pbs_version = 23.06.06.

In the previous version, when using -V, `Variable_list` in `qstat` had all env vars. 
But in the later version, nothing appended to the `Variable_list`.

`-v` option works well though.

My command was 
```
qsub work.sh 
```
and the script had `#PBS -V`.

```
qsub -V work.sh 
```
did not worked too.

**Comment by vchlum** [comment]
Hi! This is a known error. It is already fixed (#2602).
